# Generated by Django 4.2 on 2024-11-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_m',
            old_name='myfile',
            new_name='my_file',
        ),
        migrations.RenameField(
            model_name='note_m',
            old_name='no_con',
            new_name='note_content',
        ),
        migrations.RenameField(
            model_name='note_m',
            old_name='no_title',
            new_name='note_title',
        ),
        migrations.RemoveField(
            model_name='note_m',
            name='crated',
        ),
    ]
