# Generated by Django 4.2 on 2024-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='name',
            new_name='uname',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
