# Generated by Django 4.2 on 2024-11-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_myfile_note_m_my_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note_m',
            new_name='note_tbl',
        ),
    ]
