# Generated by Django 4.2 on 2024-11-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_note_m_note_tbl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note_tbl',
            new_name='nodetbl',
        ),
        migrations.RenameField(
            model_name='nodetbl',
            old_name='my_file',
            new_name='myfile',
        ),
        migrations.RenameField(
            model_name='nodetbl',
            old_name='note_content',
            new_name='no_con',
        ),
        migrations.RenameField(
            model_name='nodetbl',
            old_name='note_title',
            new_name='no_title',
        ),
    ]
